version: '3.8'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data'
      - ./sql/DEV:/docker-entrypoint-initdb.d
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_JPA_HIBERNATE_DDL-AUTO: validate
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_PROPERTIES_HIBERNATE_SEARCH_DEFAULT_INDEXBASE: /lucene
    volumes:
      - logs:/logs
      - lucene:/lucene
    depends_on:
      - db
volumes:
  database-data:
  lucene:
  logs:
