server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      pool-name: HikariPoolzzz
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false
logging:
  level:
    org.atmosphere: INFO
    org.springframework: INFO
    io.horrorshow: INFO
    com.zaxxer: INFO
    root: INFO

