# verify that the with 'set this!' marked lines fit your environment
server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        search:
          lucene_version: LATEST
          default:
            directory_provider: filesystem
            indexBase: /D_AppContent/SOULHub/hibernate-search-idx # set this!
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # set this!
    username: postgres # set this!
    password: postgres # set this!
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      pool-name: HikariPoolzzz
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  mail:
    host: host.host.com # set this!
    port: 587 # set this!
    protocol: smtp
    username: USERNAME # set this!
    password: PASSWORD # set this!
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 8000
# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false
logging:
  level:
    org.atmosphere: INFO
    org.springframework: INFO
    io.horrorshow: DEBUG
    com.zaxxer: INFO
    root: INFO
  file:
    name: /D_AppContent/SOULHub/logs/soulhub.log # set this!
    clean-history-on-start: true
