server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        search:
          lucene_version: LATEST
          default:
            directory_provider: filesystem
            indexBase: /D_AppContent/SOULHub/hibernate-search-idx
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      pool-name: HikariPoolzzz
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  mail:
    host: host.host.com
    port: 587
    protocol: smtp
    username: USERNAME
    password: PASSWORD
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 8000
# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false
logging:
  level:
    org.atmosphere: INFO
    org.springframework: INFO
    io.horrorshow: DEBUG
    com.zaxxer: INFO
    root: INFO
